module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./screens/**/*.{js,jsx,ts,tsx}",
    "./navigation/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        paper: "#DDD3BD",
        "paper-light": "#E3DAC4",
        "paper-deep": "#CFC4AB",
        ink: "#1B1711",
        "ink-muted": "#564B3F",
        "ink-soft": "#736857",
        terracotta: "#B14026",
        "terracotta-shadow": "#8E311B",
        "terracotta-soft": "#D9B19F",
        olive: "#4F573A",
        "olive-soft": "#A8AE94",
        rule: "#BFB39B",
        "rule-soft": "#CEC4AD",
      },
      fontFamily: {
        serif: ["Fraunces_500Medium"],
        "serif-italic": ["Fraunces_500Medium_Italic"],
        "serif-semibold": ["Fraunces_600SemiBold"],
        "serif-bold": ["Fraunces_700Bold"],
        sans: ["HankenGrotesk_400Regular"],
        "sans-medium": ["HankenGrotesk_500Medium"],
        "sans-semibold": ["HankenGrotesk_600SemiBold"],
        "sans-bold": ["HankenGrotesk_700Bold"],
        jakarta: ["PlusJakartaSans_500Medium"],
        "jakarta-semibold": ["PlusJakartaSans_600SemiBold"],
        "jakarta-bold": ["PlusJakartaSans_700Bold"],
        "jakarta-extrabold": ["PlusJakartaSans_800ExtraBold"],
      },
    },
  },
  plugins: [],
};
