const FLAG_CDN = "https://flagcdn.com/w320";

const COUNTRY_CODES = {
  england: "gb-eng",
  scotland: "gb-sct",
  wales: "gb-wls",
  "northern ireland": "gb-nir",
  argentina: "ar",
  brazil: "br",
  france: "fr",
  germany: "de",
  spain: "es",
  portugal: "pt",
  italy: "it",
  netherlands: "nl",
  belgium: "be",
  croatia: "hr",
  uruguay: "uy",
  colombia: "co",
  mexico: "mx",
  "united states": "us",
  usa: "us",
  canada: "ca",
  japan: "jp",
  "south korea": "kr",
  "korea republic": "kr",
  australia: "au",
  morocco: "ma",
  senegal: "sn",
  ghana: "gh",
  nigeria: "ng",
  cameroon: "cm",
  "ivory coast": "ci",
  "cote d'ivoire": "ci",
  egypt: "eg",
  algeria: "dz",
  tunisia: "tn",
  "south africa": "za",
  mali: "ml",
  "burkina faso": "bf",
  "dr congo": "cd",
  "congo dr": "cd",
  guinea: "gn",
  zambia: "zm",
  "cape verde": "cv",
  gabon: "ga",
  benin: "bj",
  togo: "tg",
  angola: "ao",
  mozambique: "mz",
  kenya: "ke",
  tanzania: "tz",
  uganda: "ug",
  ethiopia: "et",
  zimbabwe: "zw",
  libya: "ly",
  sudan: "sd",
  mauritania: "mr",
  gambia: "gm",
  "sierra leone": "sl",
  liberia: "lr",
  niger: "ne",
  chad: "td",
  botswana: "bw",
  namibia: "na",
  malawi: "mw",
  rwanda: "rw",
  burundi: "bi",
  "equatorial guinea": "gq",
  "guinea-bissau": "gw",
  comoros: "km",
  madagascar: "mg",
  switzerland: "ch",
  austria: "at",
  poland: "pl",
  ukraine: "ua",
  russia: "ru",
  serbia: "rs",
  denmark: "dk",
  sweden: "se",
  norway: "no",
  finland: "fi",
  iceland: "is",
  ireland: "ie",
  "republic of ireland": "ie",
  greece: "gr",
  turkey: "tr",
  czechia: "cz",
  "czech republic": "cz",
  slovakia: "sk",
  slovenia: "si",
  hungary: "hu",
  romania: "ro",
  bulgaria: "bg",
  albania: "al",
  "north macedonia": "mk",
  montenegro: "me",
  "bosnia and herzegovina": "ba",
  kosovo: "xk",
  georgia: "ge",
  armenia: "am",
  azerbaijan: "az",
  israel: "il",
  "saudi arabia": "sa",
  qatar: "qa",
  "united arab emirates": "ae",
  uae: "ae",
  iran: "ir",
  iraq: "iq",
  jordan: "jo",
  lebanon: "lb",
  syria: "sy",
  oman: "om",
  kuwait: "kw",
  bahrain: "bh",
  yemen: "ye",
  china: "cn",
  "china pr": "cn",
  india: "in",
  indonesia: "id",
  thailand: "th",
  vietnam: "vn",
  malaysia: "my",
  singapore: "sg",
  philippines: "ph",
  uzbekistan: "uz",
  kazakhstan: "kz",
  "new zealand": "nz",
  chile: "cl",
  peru: "pe",
  ecuador: "ec",
  paraguay: "py",
  bolivia: "bo",
  venezuela: "ve",
  panama: "pa",
  "costa rica": "cr",
  honduras: "hn",
  guatemala: "gt",
  "el salvador": "sv",
  jamaica: "jm",
  haiti: "ht",
  "trinidad and tobago": "tt",
  cuba: "cu",
  "dominican republic": "do",
};

export function getFlagUrl(teamName) {
  if (!teamName) return null;
  const code = COUNTRY_CODES[teamName.trim().toLowerCase()];
  return code ? `${FLAG_CDN}/${code}.png` : null;
}
